// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateProjectData, CreateProjectErrors, CreateProjectResponses, DeleteProjectData, DeleteProjectErrors, DeleteProjectResponses, GetProjectData, GetProjectErrors, GetProjectResponses, GetProjectsData, GetProjectsErrors, GetProjectsResponses, GetRepositoriesData, GetRepositoriesErrors, GetRepositoriesResponses, GithubAuthorizeData, GithubAuthorizeResponses, GithubCallbackData, GithubCallbackResponses, GithubInstallData, GithubInstallErrors, GithubInstallResponses, GithubSetupCallbackData, GithubSetupCallbackErrors, GithubSetupCallbackResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutErrors, LogoutResponses, MeData, MeErrors, MeResponses, PingData, PingResponses, RefreshData, RefreshErrors, RefreshResponses, RegisterData, RegisterErrors, RegisterResponses, RootData, RootResponses, UpdateProjectData, UpdateProjectErrors, UpdateProjectResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AuthService {
    /**
     * Register
     */
    public static register<ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) {
        return (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/auth/register',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Login
     */
    public static login<ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) {
        return (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Refresh
     */
    public static refresh<ThrowOnError extends boolean = false>(options?: Options<RefreshData, ThrowOnError>) {
        return (options?.client ?? client).post<RefreshResponses, RefreshErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/auth/refresh',
            ...options
        });
    }
    
    /**
     * Logout
     */
    public static logout<ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) {
        return (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({ url: '/api/auth/logout', ...options });
    }
    
    /**
     * Me
     */
    public static me<ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>) {
        return (options?.client ?? client).get<MeResponses, MeErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/auth/me',
            ...options
        });
    }
    
    /**
     * Github Authorize
     *
     * Redirect the user to GitHub's OAuth consent page for login.
     */
    public static githubAuthorize<ThrowOnError extends boolean = false>(options?: Options<GithubAuthorizeData, ThrowOnError>) {
        return (options?.client ?? client).get<GithubAuthorizeResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/auth/github/authorize',
            ...options
        });
    }
    
    /**
     * Github Callback
     */
    public static githubCallback<ThrowOnError extends boolean = false>(options?: Options<GithubCallbackData, ThrowOnError>) {
        return (options?.client ?? client).get<GithubCallbackResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/auth/github/callback',
            ...options
        });
    }
}

export class IntegrationsService {
    /**
     * Github Install
     *
     * Start a GitHub App installation (login required).
     *
     * Sets a CSRF ``state`` in the session so ``/setup-callback`` can verify the
     * redirect came from us. See ``docs/github-oauth-and-app-install.md``.
     */
    public static githubInstall<ThrowOnError extends boolean = false>(options?: Options<GithubInstallData, ThrowOnError>) {
        return (options?.client ?? client).get<GithubInstallResponses, GithubInstallErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/integrations/github/install',
            ...options
        });
    }
    
    /**
     * Github Setup Callback
     *
     * Handle the GitHub App Setup URL redirect after installation.
     *
     * Links the installation when possible, otherwise stashes it and routes
     * through OAuth. See ``docs/github-oauth-and-app-install.md`` for the full
     * scenario table and security model.
     */
    public static githubSetupCallback<ThrowOnError extends boolean = false>(options?: Options<GithubSetupCallbackData, ThrowOnError>) {
        return (options?.client ?? client).get<GithubSetupCallbackResponses, GithubSetupCallbackErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/integrations/github/setup-callback',
            ...options
        });
    }
}

export class ProjectsService {
    /**
     * Get Projects Route
     */
    public static getProjects<ThrowOnError extends boolean = false>(options?: Options<GetProjectsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetProjectsResponses, GetProjectsErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/projects/',
            ...options
        });
    }
    
    /**
     * Create Project Route
     */
    public static createProject<ThrowOnError extends boolean = false>(options: Options<CreateProjectData, ThrowOnError>) {
        return (options.client ?? client).post<CreateProjectResponses, CreateProjectErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/projects/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Project Route
     */
    public static deleteProject<ThrowOnError extends boolean = false>(options: Options<DeleteProjectData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteProjectResponses, DeleteProjectErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/projects/{id}',
            ...options
        });
    }
    
    /**
     * Get Project Route
     */
    public static getProject<ThrowOnError extends boolean = false>(options: Options<GetProjectData, ThrowOnError>) {
        return (options.client ?? client).get<GetProjectResponses, GetProjectErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/projects/{id}',
            ...options
        });
    }
    
    /**
     * Update Project Route
     */
    public static updateProject<ThrowOnError extends boolean = false>(options: Options<UpdateProjectData, ThrowOnError>) {
        return (options.client ?? client).patch<UpdateProjectResponses, UpdateProjectErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/projects/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class RepositoriesService {
    /**
     * Get Repositories Route
     */
    public static getRepositories<ThrowOnError extends boolean = false>(options?: Options<GetRepositoriesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetRepositoriesResponses, GetRepositoriesErrors, ThrowOnError>({
            responseType: 'json',
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/repositories/',
            ...options
        });
    }
}

export class UtilsService {
    /**
     * Ping
     */
    public static ping<ThrowOnError extends boolean = false>(options?: Options<PingData, ThrowOnError>) {
        return (options?.client ?? client).get<PingResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/utils/ping',
            ...options
        });
    }
}

export class DefaultService {
    /**
     * Root
     */
    public static root<ThrowOnError extends boolean = false>(options?: Options<RootData, ThrowOnError>) {
        return (options?.client ?? client).get<RootResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/',
            ...options
        });
    }
}
