// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AuthResponse
 */
export type AuthResponse = {
    user: UserPublic;
    /**
     * Message
     */
    message?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Repository Ids
     */
    repository_ids?: Array<number> | null;
};

/**
 * ProjectPublic
 */
export type ProjectPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Repositories
     */
    repositories?: Array<RepositoryPublic>;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Repository Ids
     */
    repository_ids?: Array<number> | null;
};

/**
 * RepositoryPublic
 */
export type RepositoryPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Github Id
     */
    github_id: number;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Repo Name
     */
    repo_name: string;
    /**
     * Url
     */
    url: string | null;
    /**
     * Description
     */
    description: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    201: AuthResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type GithubAuthorizeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/github/authorize';
};

export type GithubAuthorizeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GithubCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/github/callback';
};

export type GithubCallbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GithubInstallData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/github/install';
};

export type GithubInstallErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GithubInstallError = GithubInstallErrors[keyof GithubInstallErrors];

export type GithubInstallResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GithubSetupCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/github/setup-callback';
};

export type GithubSetupCallbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GithubSetupCallbackError = GithubSetupCallbackErrors[keyof GithubSetupCallbackErrors];

export type GithubSetupCallbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetGithubRepositoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/github/repositories';
};

export type GetGithubRepositoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGithubRepositoriesError = GetGithubRepositoriesErrors[keyof GetGithubRepositoriesErrors];

export type GetGithubRepositoriesResponses = {
    /**
     * Response Get Github Repositories
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetGithubRepositoriesResponse = GetGithubRepositoriesResponses[keyof GetGithubRepositoriesResponses];

export type GetProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/';
};

export type GetProjectsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectsError = GetProjectsErrors[keyof GetProjectsErrors];

export type GetProjectsResponses = {
    /**
     * Response Get Projects
     *
     * Successful Response
     */
    200: Array<ProjectPublic>;
};

export type GetProjectsResponse = GetProjectsResponses[keyof GetProjectsResponses];

export type CreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/projects/';
};

export type CreateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Successful Response
     */
    201: ProjectPublic;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type DeleteProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type GetProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    body: ProjectUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type UpdateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/utils/ping';
};

export type PingResponses = {
    /**
     * Response Ping
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type PingResponse = PingResponses[keyof PingResponses];

export type RootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootResponses = {
    /**
     * Response Root
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RootResponse = RootResponses[keyof RootResponses];
