// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AuthResponse
 */
export type AuthResponse = {
    user: UserPublic;
    /**
     * Message
     */
    message?: string;
};

/**
 * ErrorDetail
 *
 * Body shape of a raised HTTPException: {"detail": "..."}.
 */
export type ErrorDetail = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * GithubInstallationPublic
 *
 * A GitHub App installation linked to the user.
 *
 * ``account_type`` is the GitHub account kind (``User`` or
 * ``Organization``) and ``account_login`` the account it is installed on.
 */
export type GithubInstallationPublic = {
    /**
     * Installation Id
     */
    installation_id: string;
    /**
     * Account Login
     */
    account_login: string;
    /**
     * Account Type
     */
    account_type: 'User' | 'Organization';
    /**
     * Suspended At
     */
    suspended_at: string | null;
};

/**
 * GithubStatus
 *
 * Setup state of the user's GitHub integration and app installation.
 */
export type GithubStatus = {
    /**
     * Account Linked
     */
    account_linked: boolean;
    /**
     * App Installed
     */
    app_installed: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PaginatedResponse[TimeEntryPublic]
 */
export type PaginatedResponseTimeEntryPublic = {
    /**
     * Items
     */
    items: Array<TimeEntryPublic>;
    /**
     * Total
     */
    total: number;
    /**
     * Skip
     */
    skip: number;
    /**
     * Limit
     */
    limit: number;
};

/**
 * ProjectColumnItem
 */
export type ProjectColumnItem = {
    /**
     * Kind
     */
    kind: 'TIME' | 'DURATION' | 'SOURCE' | 'DESCRIPTION' | 'CUSTOM';
    /**
     * Name
     */
    name: string;
    /**
     * Builtin
     */
    builtin?: boolean;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Repository Ids
     */
    repository_ids?: Array<number> | null;
};

/**
 * ProjectPublic
 */
export type ProjectPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Repositories
     */
    repositories?: Array<RepositoryPublic>;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Repository Ids
     */
    repository_ids?: Array<number> | null;
};

/**
 * RepositoryPublic
 */
export type RepositoryPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Github Id
     */
    github_id: number;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Repo Name
     */
    repo_name: string;
    /**
     * Url
     */
    url: string | null;
    /**
     * Description
     */
    description: string | null;
};

/**
 * TimeEntryCreate
 */
export type TimeEntryCreate = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
};

/**
 * TimeEntryPublic
 */
export type TimeEntryPublic = {
    /**
     * Id
     */
    id?: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
    /**
     * Project Id
     */
    project_id: string;
};

/**
 * TimeEntryUpdate
 */
export type TimeEntryUpdate = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Start Time
     */
    start_time?: string | null;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * Resource already exists
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    201: AuthResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Insufficient permissions
     */
    403: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type GetColumnsData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}/columns';
};

export type GetColumnsErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Resource not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetColumnsError = GetColumnsErrors[keyof GetColumnsErrors];

export type GetColumnsResponses = {
    /**
     * Response Get Columns
     *
     * Successful Response
     */
    200: Array<ProjectColumnItem>;
};

export type GetColumnsResponse = GetColumnsResponses[keyof GetColumnsResponses];

export type SetColumnsData = {
    /**
     * Columns
     */
    body: Array<ProjectColumnItem>;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}/columns';
};

export type SetColumnsErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Resource not found
     */
    404: ErrorDetail;
    /**
     * Validation failed
     */
    422: ErrorDetail;
};

export type SetColumnsError = SetColumnsErrors[keyof SetColumnsErrors];

export type SetColumnsResponses = {
    /**
     * Response Set Columns
     *
     * Successful Response
     */
    200: Array<ProjectColumnItem>;
};

export type SetColumnsResponse = SetColumnsResponses[keyof SetColumnsResponses];

export type GithubAuthorizeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/github/authorize';
};

export type GithubAuthorizeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GithubCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/github/callback';
};

export type GithubCallbackErrors = {
    /**
     * Invalid request
     */
    400: ErrorDetail;
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Insufficient permissions
     */
    403: ErrorDetail;
};

export type GithubCallbackError = GithubCallbackErrors[keyof GithubCallbackErrors];

export type GithubCallbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GithubStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/github/status';
};

export type GithubStatusErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GithubStatusError = GithubStatusErrors[keyof GithubStatusErrors];

export type GithubStatusResponses = {
    /**
     * Successful Response
     */
    200: GithubStatus;
};

export type GithubStatusResponse = GithubStatusResponses[keyof GithubStatusResponses];

export type GithubInstallationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/github/installations';
};

export type GithubInstallationsErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GithubInstallationsError = GithubInstallationsErrors[keyof GithubInstallationsErrors];

export type GithubInstallationsResponses = {
    /**
     * Response Github Installations
     *
     * Successful Response
     */
    200: Array<GithubInstallationPublic>;
};

export type GithubInstallationsResponse = GithubInstallationsResponses[keyof GithubInstallationsResponses];

export type GithubInstallData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/github/install';
};

export type GithubInstallErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GithubInstallError = GithubInstallErrors[keyof GithubInstallErrors];

export type GithubInstallResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GithubSetupCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/github/setup-callback';
};

export type GithubSetupCallbackErrors = {
    /**
     * Invalid request
     */
    400: ErrorDetail;
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GithubSetupCallbackError = GithubSetupCallbackErrors[keyof GithubSetupCallbackErrors];

export type GithubSetupCallbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/';
};

export type GetProjectsErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectsError = GetProjectsErrors[keyof GetProjectsErrors];

export type GetProjectsResponses = {
    /**
     * Response Get Projects
     *
     * Successful Response
     */
    200: Array<ProjectPublic>;
};

export type GetProjectsResponse = GetProjectsResponses[keyof GetProjectsResponses];

export type CreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/projects/';
};

export type CreateProjectErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Successful Response
     */
    201: ProjectPublic;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type DeleteProjectErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Resource not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type GetProjectErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Resource not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    body: ProjectUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type UpdateProjectErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Resource not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type GetRepositoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/repositories/';
};

export type GetRepositoriesErrors = {
    /**
     * Authentication required
     */
    401: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * GitHub account not linked or app not installed
     */
    428: ErrorDetail;
};

export type GetRepositoriesError = GetRepositoriesErrors[keyof GetRepositoriesErrors];

export type GetRepositoriesResponses = {
    /**
     * Response Get Repositories
     *
     * Successful Response
     */
    200: Array<RepositoryPublic>;
};

export type GetRepositoriesResponse = GetRepositoriesResponses[keyof GetRepositoriesResponses];

export type GetEntriesForProjectData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/projects/{id}/entries';
};

export type GetEntriesForProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEntriesForProjectError = GetEntriesForProjectErrors[keyof GetEntriesForProjectErrors];

export type GetEntriesForProjectResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseTimeEntryPublic;
};

export type GetEntriesForProjectResponse = GetEntriesForProjectResponses[keyof GetEntriesForProjectResponses];

export type CreateTimeEntryData = {
    body: TimeEntryCreate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}/entries';
};

export type CreateTimeEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTimeEntryError = CreateTimeEntryErrors[keyof CreateTimeEntryErrors];

export type CreateTimeEntryResponses = {
    /**
     * Successful Response
     */
    201: TimeEntryPublic;
};

export type CreateTimeEntryResponse = CreateTimeEntryResponses[keyof CreateTimeEntryResponses];

export type DeleteTimeEntryData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}/entries/{entry_id}';
};

export type DeleteTimeEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTimeEntryError = DeleteTimeEntryErrors[keyof DeleteTimeEntryErrors];

export type DeleteTimeEntryResponses = {
    /**
     * Successful Response
     */
    200: TimeEntryPublic;
};

export type DeleteTimeEntryResponse = DeleteTimeEntryResponses[keyof DeleteTimeEntryResponses];

export type GetTimeEntryData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}/entries/{entry_id}';
};

export type GetTimeEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTimeEntryError = GetTimeEntryErrors[keyof GetTimeEntryErrors];

export type GetTimeEntryResponses = {
    /**
     * Successful Response
     */
    200: TimeEntryPublic;
};

export type GetTimeEntryResponse = GetTimeEntryResponses[keyof GetTimeEntryResponses];

export type UpdateTimeEntryData = {
    body: TimeEntryUpdate;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}/entries/{entry_id}';
};

export type UpdateTimeEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTimeEntryError = UpdateTimeEntryErrors[keyof UpdateTimeEntryErrors];

export type UpdateTimeEntryResponses = {
    /**
     * Successful Response
     */
    200: TimeEntryPublic;
};

export type UpdateTimeEntryResponse = UpdateTimeEntryResponses[keyof UpdateTimeEntryResponses];

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/utils/ping';
};

export type PingResponses = {
    /**
     * Response Ping
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type PingResponse = PingResponses[keyof PingResponses];

export type RootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootResponses = {
    /**
     * Response Root
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RootResponse = RootResponses[keyof RootResponses];
