// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AuthResponse
 */
export type AuthResponse = {
    user: UserPublic;
    /**
     * Message
     */
    message?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ProjectPublic
 */
export type ProjectPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RegisterApiAuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterApiAuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiAuthRegisterPostError = RegisterApiAuthRegisterPostErrors[keyof RegisterApiAuthRegisterPostErrors];

export type RegisterApiAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: AuthResponse;
};

export type RegisterApiAuthRegisterPostResponse = RegisterApiAuthRegisterPostResponses[keyof RegisterApiAuthRegisterPostResponses];

export type LoginApiAuthLoginPostData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type RefreshApiAuthRefreshPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshApiAuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshApiAuthRefreshPostError = RefreshApiAuthRefreshPostErrors[keyof RefreshApiAuthRefreshPostErrors];

export type RefreshApiAuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: AuthResponse;
};

export type RefreshApiAuthRefreshPostResponse = RefreshApiAuthRefreshPostResponses[keyof RefreshApiAuthRefreshPostResponses];

export type LogoutApiAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutApiAuthLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutApiAuthLogoutPostError = LogoutApiAuthLogoutPostErrors[keyof LogoutApiAuthLogoutPostErrors];

export type LogoutApiAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiAuthLogoutPostResponse = LogoutApiAuthLogoutPostResponses[keyof LogoutApiAuthLogoutPostResponses];

export type MeApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeApiAuthMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeApiAuthMeGetError = MeApiAuthMeGetErrors[keyof MeApiAuthMeGetErrors];

export type MeApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type MeApiAuthMeGetResponse = MeApiAuthMeGetResponses[keyof MeApiAuthMeGetResponses];

export type GithubAuthorizeApiAuthGithubAuthorizeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/github/authorize';
};

export type GithubAuthorizeApiAuthGithubAuthorizeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GithubCallbackApiAuthGithubCallbackGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/github/callback';
};

export type GithubCallbackApiAuthGithubCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GithubInstallApiAuthGithubInstallGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/github/install';
};

export type GithubInstallApiAuthGithubInstallGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GithubInstallApiAuthGithubInstallGetError = GithubInstallApiAuthGithubInstallGetErrors[keyof GithubInstallApiAuthGithubInstallGetErrors];

export type GithubInstallApiAuthGithubInstallGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GithubSetupCallbackApiAuthGithubSetupCallbackGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/github/setup-callback';
};

export type GithubSetupCallbackApiAuthGithubSetupCallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GithubSetupCallbackApiAuthGithubSetupCallbackGetError = GithubSetupCallbackApiAuthGithubSetupCallbackGetErrors[keyof GithubSetupCallbackApiAuthGithubSetupCallbackGetErrors];

export type GithubSetupCallbackApiAuthGithubSetupCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetGithubRepositoriesApiAuthGithubRepositoriesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/github/repositories';
};

export type GetGithubRepositoriesApiAuthGithubRepositoriesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGithubRepositoriesApiAuthGithubRepositoriesGetError = GetGithubRepositoriesApiAuthGithubRepositoriesGetErrors[keyof GetGithubRepositoriesApiAuthGithubRepositoriesGetErrors];

export type GetGithubRepositoriesApiAuthGithubRepositoriesGetResponses = {
    /**
     * Response Get Github Repositories Api Auth Github Repositories Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetGithubRepositoriesApiAuthGithubRepositoriesGetResponse = GetGithubRepositoriesApiAuthGithubRepositoriesGetResponses[keyof GetGithubRepositoriesApiAuthGithubRepositoriesGetResponses];

export type GetProjectsRouteApiProjectsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/';
};

export type GetProjectsRouteApiProjectsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectsRouteApiProjectsGetError = GetProjectsRouteApiProjectsGetErrors[keyof GetProjectsRouteApiProjectsGetErrors];

export type GetProjectsRouteApiProjectsGetResponses = {
    /**
     * Response Get Projects Route Api Projects  Get
     *
     * Successful Response
     */
    200: Array<ProjectPublic>;
};

export type GetProjectsRouteApiProjectsGetResponse = GetProjectsRouteApiProjectsGetResponses[keyof GetProjectsRouteApiProjectsGetResponses];

export type CreateProjectRouteApiProjectsPostData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/projects/';
};

export type CreateProjectRouteApiProjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectRouteApiProjectsPostError = CreateProjectRouteApiProjectsPostErrors[keyof CreateProjectRouteApiProjectsPostErrors];

export type CreateProjectRouteApiProjectsPostResponses = {
    /**
     * Successful Response
     */
    201: ProjectPublic;
};

export type CreateProjectRouteApiProjectsPostResponse = CreateProjectRouteApiProjectsPostResponses[keyof CreateProjectRouteApiProjectsPostResponses];

export type DeleteProjectRouteApiProjectsIdDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects/{id}';
};

export type DeleteProjectRouteApiProjectsIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetProjectRouteApiProjectsIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type GetProjectRouteApiProjectsIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectRouteApiProjectsIdGetError = GetProjectRouteApiProjectsIdGetErrors[keyof GetProjectRouteApiProjectsIdGetErrors];

export type GetProjectRouteApiProjectsIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type GetProjectRouteApiProjectsIdGetResponse = GetProjectRouteApiProjectsIdGetResponses[keyof GetProjectRouteApiProjectsIdGetResponses];

export type PingApiPingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ping';
};

export type PingApiPingGetResponses = {
    /**
     * Response Ping Api Ping Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type PingApiPingGetResponse = PingApiPingGetResponses[keyof PingApiPingGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Response Root  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];
