"""add account id and email to integration model

Revision ID: 191e202df747
Revises: e194ddb37de3
Create Date: 2026-03-05 23:21:48.631190

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "191e202df747"
down_revision: str | Sequence[str] | None = "e194ddb37de3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "integration",
        sa.Column(
            "account_id", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False
        ),
    )
    op.add_column(
        "integration",
        sa.Column(
            "account_email",
            sqlmodel.sql.sqltypes.AutoString(length=320),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_integration_account_id"), "integration", ["account_id"], unique=False
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_index(op.f("ix_integration_account_id"), table_name="integration")
    op.drop_column("integration", "account_email")
    op.drop_column("integration", "account_id")
    # ### end Alembic commands ###
