"""refactor_repository_to_many_to_many_with_projects

Revision ID: 8c40f229d264
Revises: b7f2e6a91c34
Create Date: 2026-08-03 18:53:02.102195

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c40f229d264"
down_revision: str | Sequence[str] | None = "b7f2e6a91c34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projectrepository",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id", "repository_id"),
    )
    op.add_column("repository", sa.Column("github_id", sa.Integer(), nullable=False))
    op.add_column(
        "repository",
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "repository",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_repository_full_name"), "repository", ["full_name"], unique=False
    )
    op.create_index(
        op.f("ix_repository_github_id"), "repository", ["github_id"], unique=True
    )
    op.drop_constraint(
        op.f("repository_project_id_fkey"), "repository", type_="foreignkey"
    )
    op.drop_column("repository", "project_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repository",
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("repository_project_id_fkey"),
        "repository",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_repository_github_id"), table_name="repository")
    op.drop_index(op.f("ix_repository_full_name"), table_name="repository")
    op.drop_column("repository", "description")
    op.drop_column("repository", "full_name")
    op.drop_column("repository", "github_id")
    op.drop_table("projectrepository")
    # ### end Alembic commands ###
