"""Add transparent token encryption

Revision ID: e194ddb37de3
Revises: 384fcccbf21e
Create Date: 2026-03-03 02:17:28.232626

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.models.base_types import EncryptedString

# revision identifiers, used by Alembic.
revision: str = "e194ddb37de3"
down_revision: str | Sequence[str] | None = "384fcccbf21e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "integration",
        "access_token",
        existing_type=sa.VARCHAR(),
        type_=EncryptedString(),
        existing_nullable=False,
        postgresql_using="access_token::bytea",
    )
    op.alter_column(
        "integration",
        "refresh_token",
        existing_type=sa.VARCHAR(),
        type_=EncryptedString(),
        existing_nullable=True,
        postgresql_using="refresh_token::bytea",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "integration",
        "refresh_token",
        existing_type=EncryptedString(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        postgresql_using="refresh_token::text",
    )
    op.alter_column(
        "integration",
        "access_token",
        existing_type=EncryptedString(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using="access_token::text",
    )
    # ### end Alembic commands ###
