import type { ProjectPublic } from "@/client/types.gen";
import { formatDate } from "@/lib/utils";

/**
 * Central copy for all user-visible strings. Tolgee-ready: keys map
 * one-to-one for future extraction. Never hardcode UI text in components.
 */
export const strings = {
  common: {
    brand: "DevTrackr",
    signOut: "Sign out",
    cancel: "Cancel",
    save: "Save changes",
    retry: "Try again",
    goHome: "Go home",
    entries: "entries",
    close: "Close",
  },
  nav: {
    projects: "Projects",
    logbook: "Logbook",
    insights: "Insights",
    settings: "Settings",
  },
  settings: {
    title: "Settings",
    subtitle: "Connections, providers, and logbook formatting.",
    logbookColumns: "Logbook columns",
    columnAdd: "Add column",
    columnNamePlaceholder: "Column name",
    columnRemoveLabel: "Remove column",
    columnMoveUp: "Move up",
    columnMoveDown: "Move down",
    columnTime: "TIME",
    columnDuration: "DURATION",
    columnSource: "SOURCE",
    columnDescription: "DESCRIPTION",
    columnCustom: "CUSTOM",
    githubTitle: "GitHub",
    githubAccountTypeUser: "User account",
    githubAccountTypeOrg: "Organization",
    githubSuspended: "Suspended",
    githubManageLink: "Manage on GitHub",
    githubManageHint: "Manage repo access and uninstall the app on GitHub.",
  },
  projects: {
    title: "Projects",
    subtitle: "All your tracked development projects in one place.",
    newProject: "New project",
    emptyTitle: "No projects yet",
    emptyDescription:
      "Create your first project to start tracking time and commits.",
    active: "Active",
    inactive: "Inactive",
    totalLabel: "Total projects",
    activeLabel: "Active",
    inactiveLabel: "Inactive",
    noDescription: "No description",
    updatedAt: (iso: string) => `Updated ${formatDate(iso)}`,
    createTitle: "New project",
    createDescription: "Projects track time and commits for one codebase.",
    nameLabel: "Name",
    namePlaceholder: "My project",
    nameRequired: "Name is required",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Optional notes about this project",
    createButton: "Create project",
    createdToast: "Project created",
    deleteTitle: "Delete project",
    deleteDescription:
      "This project and its tracked entries will be removed. This cannot be undone.",
    deleteButton: "Delete project",
    deleteLabel: "Delete project",
    deletedToast: "Project deleted",
    updateLabel: "Update project",
    updateTitle: "Update project",
    updateDescription: "Change the name or notes for this project.",
    updateButton: "Update project",
    updatedToast: "Project updated",
    detailToast: (project: ProjectPublic) =>
      `${project.name} · ${project.is_active ? strings.projects.active : strings.projects.inactive} · Created ${formatDate(project.created_at)}`,
    detailErrorToast: "Couldn't load project details. Try again.",
  },
  integrations: {
    githubSetupPrompt: "Set up GitHub to sync repositories",
    githubInstallButton: "Install GitHub App",
    githubInstalledToast: "GitHub app installed, repositories synced",
    githubInstallErrorToast: "GitHub app setup didn't complete",
    githubInstallSyncErrorToast:
      "GitHub app installed, but repository sync didn't complete. Repositories will appear on next sync.",
    githubInstallSyncPartialToast:
      "GitHub app installed, but some repositories couldn't be synced. They will appear on next sync.",
    githubInstallUnauthorizedToast:
      "This GitHub App installation doesn't belong to your account.",
    githubInstallConflictToast:
      "This GitHub App installation is already linked to another account.",
    githubLoading: "Loading repositories...",
    githubError: "Could not load repositories",
    githubInstallationsError: "Could not load GitHub installations",
    repoSelectorLabel: "Repositories",
    repoSelectorDescription: "Link GitHub repositories to this project",
    repoSearchPlaceholder: "Search repositories...",
    noReposFound: "No repositories found",
    repoOpenLink: (name: string) => `Open ${name} on GitHub`,
    reposCount: (n: number) => `${n} repo${n === 1 ? "" : "s"}`,
  },
  login: {
    brand: "DevTrackr",
    title: "DevTrackr",
    tagline: "Track time, commits, and progress.",
    signInTab: "Sign in",
    createAccountTab: "Create account",
    signIn: "Sign in",
    createAccount: "Create account",
    continueWithGithub: "Continue with GitHub",
    githubLogo: "GitHub logo",
    or: "or",
    email: "Email",
    emailPlaceholder: "you@example.com",
    emailInvalid: "Enter a valid email address",
    password: "Password",
    passwordRequired: "Password is required",
    passwordMin: "Password must be at least 8 characters",
    username: "Username",
    usernameMin: "Username must be at least 2 characters",
    usernamePlaceholder: "johndoe",
    passwordPlaceholder: "********",
  },
  counter: {
    title: "Counter Page",
    currentCount: (count: number) => `Current Count: ${count}`,
    decrement: "Decrement",
    increment: "Increment",
  },
  error: {
    loadFailed: "Failed to load",
    defaultMessage: "Something went wrong. Please try again.",
    rootTitle: "Something went wrong",
    rootDescription: "An unexpected error occurred.",
  },
  empty: {
    defaultTitle: "Nothing here yet",
  },
} as const;

export type StringKey = keyof typeof strings;
